# -*- coding: utf-8 -*-
"""Untitled47.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1skmJY5GcYdLIhTyK1KNsbcIypBhdOOL0
"""

{
  "name": "sampada karne",
  "skills": ["Python", "Data structure", "MYSQL","Java"],
  "experience_level": "Intermediate",
  "preferences": {
    "desired_roles": ["Backend Developer", "Software Engineer"],
    "locations": ["Remote", "india"],
    "job_type": ["Full-Time","internship"]
  }
}

